server:
    port: 8181
    servlet:
        context-path: /hoaxify
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 5GISP_2021_etiya
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: ${DDL_AUTO:create}
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                default_schema: ${DB_SCHEMA_NAME:hoaxify}
#                check_nullability: true
#                validator:
#                    apply_to_ddl: false
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
#    output:
#        ansi:
#            enabled: always

logging:
    level:
        org:
            hibernate:
                boot: ERROR
            springframework:
                web:
                    servlet:
                        DispatcherServlet: DEBUG

#H2 storage
#spring:
#    datasource:
#        url: jdbc:h2:./devdb
#        username: sa
#    jpa:
#        hibernate:
#            ddl-auto: update